version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bucket-list-operators-db
    restart: always
    environment:
      POSTGRES_USER: bucketlist
      POSTGRES_PASSWORD: bucketlist123
      POSTGRES_DB: oasis_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
